### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by GamingIQ1** [CloudClientDev/cloudinstaller#2]
idk how to install

**Comment by GamingIQ1** [comment]
im on mac btw

**Comment by RealPacket** [comment]
literally just install the .NET framework and then execute it or build it with the .NET SDK

**Comment by Hobbyshop** [comment]
You download the client from their [webiste](https://cloudmc.dev/).

**Comment by jordoncodes** [comment]
> idk how to install

the installer doesnt work on mac you have to download the .jar and use it as a forge mod.
